export const provinceData = [
  { id: "AC", description: "Aceh" },
  { id: "SU", description: "Sumatera Utara" },
  { id: "SB", description: "Sumatera Barat" },
  { id: "RI", description: "Riau" },
  { id: "KR", description: "Kepulauan Riau" },
  { id: "JA", description: "Jambi" },
  { id: "SS", description: "Sumatera Selatan" },
  { id: "BB", description: "Bangka Belitung" },
  { id: "BE", description: "Bengkulu" },
  { id: "LA", description: "Lampung" },
  { id: "JK", description: "DKI Jakarta" },
  { id: "JB", description: "Jawa Barat" },
  { id: "BT", description: "Banten" },
  { id: "JT", description: "Jawa Tengah" },
  { id: "YO", description: "DI Yogyakarta" },
  { id: "JI", description: "Jawa Timur" },
  { id: "BA", description: "Bali" },
  { id: "NB", description: "Nusa Tenggara Barat" },
  { id: "NT", description: "Nusa Tenggara Timur" },
  { id: "KB", description: "Kalimantan Barat" },
  { id: "KT", description: "Kalimantan Tengah" },
  { id: "KS", description: "Kalimantan Selatan" },
  { id: "KI", description: "Kalimantan Timur" },
  { id: "KU", description: "Kalimantan Utara" },
  { id: "SA", description: "Sulawesi Utara" },
  { id: "ST", description: "Sulawesi Tengah" },
  { id: "SG", description: "Sulawesi Tenggara" },
  { id: "SR", description: "Sulawesi Barat" },
  { id: "SN", description: "Sulawesi Selatan" },
  { id: "GO", description: "Gorontalo" },
  { id: "MA", description: "Maluku" },
  { id: "MU", description: "Maluku Utara" },
  { id: "PP", description: "Papua" },
  { id: "PB", description: "Papua Barat" },
  { id: "PT", description: "Papua Tengah" },
  { id: "PS", description: "Papua Selatan" },
  { id: "PG", description: "Papua Pegunungan" },
  { id: "PD", description: "Papua Barat Daya" }
];
